In [1]:
import pandas as pd
import numpy as np

In [2]:
review = pd.read_csv('review.csv')
review

,Unnamed: 0,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,0,xQY8N_XvtGbearJ5X4QryQ,OwjRMXRC0KyPrIlcjaXeFQ,-MhfebM0QIsKt87iDN-FNw,2,5,0,0,"As someone who has worked with many museums, I...",2015-04-15 05:21:16
1,1,UmFMZ8PyXZTY2QcwzsfQYA,nIJD_7ZXHq-FX8byPMOkMQ,lbrU8StCq3yDfr-QMnGrmQ,1,1,1,0,I am actually horrified this place is still in...,2013-12-07 03:16:52
2,2,LG2ZaYiOgpr2DK_90pYjNw,V34qejxNsCbcgD8C0HVk-Q,HQl28KMwrEKHqhFrrDqVNQ,5,1,0,0,I love Deagan's. I do. I really do. The atmosp...,2015-12-05 03:18:11
3,3,i6g_oA9Yf9Y31qt0wibXpw,ofKDkJKXSKZXu5xJNGiiBQ,5JxlZaqCnk1MnbgRirs40Q,1,0,0,0,"Dismal, lukewarm, defrosted-tasting ""TexMex"" g...",2011-05-27 05:30:52
4,4,6TdNDKywdbjoTkizeMce8A,UgMW8bLE0QMJDCkQ1Ax5Mg,IS4cv902ykd8wj1TR0N3-A,4,0,0,0,"Oh happy day, finally have a Canes near my cas...",2017-01-14 21:56:57
...,...,...,...,...,...,...,...,...,...,...
8021117,8021117,LAzw2u1ucY722ryLEXHdgg,6DMFD3BRp-MVzDQelRx5UQ,XW2kaXdahICaJ27A0dhGHg,1,1,0,1,"Fricken unbelievable, I ordered 2 space heater...",2019-12-11 01:07:06
8021118,8021118,gMDU14Fa_DVIcPvsKtubJA,_g6P8H3-qfbz1FxbffS68g,IsoLzudHC50oJLiEWpwV-w,3,1,3,1,Solid American food with a southern comfort fl...,2019-12-10 04:15:00
8021119,8021119,EcY_p50zPIQ2R6rf6-5CjA,Scmyz7MK4TbXXYcaLZxIxQ,kDCyqlYcstqnoqnfBRS5Og,5,15,6,13,I'm honestly not sure how I have never been to...,2019-06-06 15:01:53
8021120,8021120,-z_MM0pAf9RtZbyPlphTlA,lBuAACBEThaQHQGMzAlKpg,VKVDDHKtsdrnigeIf9S8RA,3,2,0,0,Food was decent but I will say the service too...,2018-07-05 18:45:21
8021121,8021121,nK0JGgr8aO4mcFPU4pDOEA,fiA6ztHPONUkmX6yKIXyHg,2SbyRgHWuWNlq18eHAx95Q,5,2,0,2,"Oh yeah! Not only that the service was good, t...",2019-12-07 00:29:55

In [3]:
business = pd.read_csv('yelp_academic_dataset_business.csv')
business

,Unnamed: 0,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,0,f9NumwFMBDn751xgFiRbNA,The Range At Lake Norman,10913 Bailey Rd,Cornelius,NC,28031,35.462724,-80.852612,3.5,36,1,"{'BusinessAcceptsCreditCards': 'True', 'BikePa...","Active Life, Gun/Rifle Ranges, Guns & Ammo, Sh...","{'Monday': '10:0-18:0', 'Tuesday': '11:0-20:0'..."
1,1,Yzvjg0SayhoZgCljUJRF9Q,"Carlos Santo, NMD","8880 E Via Linda, Ste 107",Scottsdale,AZ,85258,33.569404,-111.890264,5.0,4,1,"{'GoodForKids': 'True', 'ByAppointmentOnly': '...","Health & Medical, Fitness & Instruction, Yoga,...",NaN
2,2,XNoUzKckATkOD1hP6vghZg,Felinus,3554 Rue Notre-Dame O,Montreal,QC,H4C 1P4,45.479984,-73.580070,5.0,5,1,NaN,"Pets, Pet Services, Pet Groomers",NaN
3,3,6OAZjbxqM5ol29BuHsil3w,Nevada House of Hose,1015 Sharp Cir,North Las Vegas,NV,89030,36.219728,-115.127725,2.5,3,0,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Hardware Stores, Home Services, Building Suppl...","{'Monday': '7:0-16:0', 'Tuesday': '7:0-16:0', ..."
4,4,51M2Kk903DFYI6gnB5I6SQ,USE MY GUY SERVICES LLC,4827 E Downing Cir,Mesa,AZ,85205,33.428065,-111.726649,4.5,26,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Home Services, Plumbing, Electricians, Handyma...","{'Monday': '0:0-0:0', 'Tuesday': '9:0-16:0', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209388,209388,9Q0fPWAjUweoFDk0kafuzQ,Nishi Sushi,9750 Weston Road,Vaughan,ON,L4H 2P2,43.838555,-79.559823,4.0,5,0,"{'Ambience': ""{'romantic': False, 'intimate': ...","Japanese, Sushi Bars, Restaurants","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
209389,209389,PotiAhtDMYMNsJCzV0oLAw,Walmart,3240 Wilkinson Blvd,Charlotte,NC,28208,35.226307,-80.893539,2.0,13,0,"{'RestaurantsPriceRange2': '1', 'BusinessParki...","Department Stores, Food, Mobile Phones, Fashio...",NaN
209390,209390,SYa2j1boLF8DcGVOYfHPcA,Five Guys,7014-590 E Camelback Rd,Scottsdale,AZ,85251,33.504062,-111.929431,3.5,97,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","American (New), Food, Burgers, Restaurants, Fa...","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
209391,209391,RSSIsgO00OuWQTRoITacpA,Indian Trail Dog Training,NaN,Indian Trail,NC,28079,35.101965,-80.599385,5.0,3,1,NaN,"Pet Services, Pet Training, Pets","{'Monday': '0:0-0:0', 'Tuesday': '7:0-19:0', '..."
209392,209392,tOcYmewXFhQeZh3V42ymwg,Kudlow Ye,"21 St Clair Avenue E, Suite 401",Toronto,ON,M4T 1L9,43.688214,-79.392756,5.0,3,1,NaN,"Tax Services, Professional Services, Accountan...","{'Monday': '9:0-18:0', 'Tuesday': '9:0-18:0', ..."

In [4]:
all_data = pd.merge(review, business, on='business_id')
all_data

,Unnamed: 0_x,review_id,user_id,business_id,stars_x,useful,funny,cool,text,date,...,state,postal_code,latitude,longitude,stars_y,review_count,is_open,attributes,categories,hours
0,0,xQY8N_XvtGbearJ5X4QryQ,OwjRMXRC0KyPrIlcjaXeFQ,-MhfebM0QIsKt87iDN-FNw,2,5,0,0,"As someone who has worked with many museums, I...",2015-04-15 05:21:16,...,NV,89109,36.112896,-115.177637,3.5,180,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Shopping, Arts & Entertainment, Art Galleries,...","{'Monday': '10:0-20:0', 'Tuesday': '10:0-20:0'..."
1,18209,t7xOZF5UKXjSpVcXLOSAgw,owbC7FP8SNAlwv6f9S5Stw,-MhfebM0QIsKt87iDN-FNw,2,2,2,0,I have been there. I believe more than once. \...,2014-03-14 08:24:25,...,NV,89109,36.112896,-115.177637,3.5,180,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Shopping, Arts & Entertainment, Art Galleries,...","{'Monday': '10:0-20:0', 'Tuesday': '10:0-20:0'..."
2,19812,MimB5Xh85rG7phUMPrShag,v9vGnjphb0Hta0lvtf5haA,-MhfebM0QIsKt87iDN-FNw,3,5,3,3,I haven't been to Las Vegas in about 15 years....,2015-10-07 22:16:59,...,NV,89109,36.112896,-115.177637,3.5,180,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Shopping, Arts & Entertainment, Art Galleries,...","{'Monday': '10:0-20:0', 'Tuesday': '10:0-20:0'..."
3,20132,sLkT7J06L4TK4PiRUFax2g,AXuHgGQoNPkiSXTxHlQc0A,-MhfebM0QIsKt87iDN-FNw,2,0,0,0,One of the few places in town you can view wor...,2015-11-18 22:20:55,...,NV,89109,36.112896,-115.177637,3.5,180,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Shopping, Arts & Entertainment, Art Galleries,...","{'Monday': '10:0-20:0', 'Tuesday': '10:0-20:0'..."
4,34353,cnV5xtm6WuyaLfot9uWbDg,LkWNo83Lg92C5V4JEyxOZA,-MhfebM0QIsKt87iDN-FNw,3,3,1,2,This is a hard one to review. I was excited to...,2010-10-10 01:27:31,...,NV,89109,36.112896,-115.177637,3.5,180,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Shopping, Arts & Entertainment, Art Galleries,...","{'Monday': '10:0-20:0', 'Tuesday': '10:0-20:0'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8021117,8016096,yJJtiOJ-p1nUkwtFEd8PWg,Mkb6AzO-2X2S5fdt6OrInQ,66uR6KGQpVNYzYXcLwvLmg,1,2,1,0,A very bad job had to do it over n still not r...,2018-08-13 20:21:19,...,OH,44109,41.418991,-81.690923,3.5,3,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Auto Repair, Automotive, Auto Detailing, Body ...","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ..."
8021118,8017300,UkhGGypImTcMYsqeNmO-kA,Lzqisc3p6b9s4CxOQPEPXw,66uR6KGQpVNYzYXcLwvLmg,5,5,1,1,I've dealt with A Touch of Class several times...,2017-04-08 20:31:17,...,OH,44109,41.418991,-81.690923,3.5,3,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Auto Repair, Automotive, Auto Detailing, Body ...","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ..."
8021119,8014945,Dh8X9r_uxhhtRU-0z-AroA,q5GPWlNDO_8xEyn0SoqYiA,gupf_nysqVXsCkmJJjIgEw,1,0,0,0,Very prompt email response.\nHe has good revie...,2019-11-12 19:25:58,...,ON,M1N 1N1,43.706165,-79.249938,3.5,3,1,{'ByAppointmentOnly': 'False'},"Professional Services, Office Cleaning, Home C...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
8021120,8017647,Y2q7-ExUvXr32_PYxad28Q,wCsohq112DNRAYWXXNnemw,gupf_nysqVXsCkmJJjIgEw,5,0,0,0,We have used TorontoCleaningSolutions & office...,2019-11-29 23:01:03,...,ON,M1N 1N1,43.706165,-79.249938,3.5,3,1,{'ByAppointmentOnly': 'False'},"Professional Services, Office Cleaning, Home C...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
8021121,8019597,No5DaA47bGRRqMnrEPQ2XQ,lEbDfbJsC70xltar8OxbHg,gupf_nysqVXsCkmJJjIgEw,5,0,0,0,I had the pleasure of hiring Toronto Cleaning ...,2019-10-15 03:51:05,...,ON,M1N 1N1,43.706165,-79.249938,3.5,3,1,{'ByAppointmentOnly': 'False'},"Professional Services, Office Cleaning, Home C...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."

In [5]:
all_data_open = all_data[all_data['is_open']==1]
all_data_open

,Unnamed: 0_x,review_id,user_id,business_id,stars_x,useful,funny,cool,text,date,...,state,postal_code,latitude,longitude,stars_y,review_count,is_open,attributes,categories,hours
0,0,xQY8N_XvtGbearJ5X4QryQ,OwjRMXRC0KyPrIlcjaXeFQ,-MhfebM0QIsKt87iDN-FNw,2,5,0,0,"As someone who has worked with many museums, I...",2015-04-15 05:21:16,...,NV,89109,36.112896,-115.177637,3.5,180,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Shopping, Arts & Entertainment, Art Galleries,...","{'Monday': '10:0-20:0', 'Tuesday': '10:0-20:0'..."
1,18209,t7xOZF5UKXjSpVcXLOSAgw,owbC7FP8SNAlwv6f9S5Stw,-MhfebM0QIsKt87iDN-FNw,2,2,2,0,I have been there. I believe more than once. \...,2014-03-14 08:24:25,...,NV,89109,36.112896,-115.177637,3.5,180,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Shopping, Arts & Entertainment, Art Galleries,...","{'Monday': '10:0-20:0', 'Tuesday': '10:0-20:0'..."
2,19812,MimB5Xh85rG7phUMPrShag,v9vGnjphb0Hta0lvtf5haA,-MhfebM0QIsKt87iDN-FNw,3,5,3,3,I haven't been to Las Vegas in about 15 years....,2015-10-07 22:16:59,...,NV,89109,36.112896,-115.177637,3.5,180,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Shopping, Arts & Entertainment, Art Galleries,...","{'Monday': '10:0-20:0', 'Tuesday': '10:0-20:0'..."
3,20132,sLkT7J06L4TK4PiRUFax2g,AXuHgGQoNPkiSXTxHlQc0A,-MhfebM0QIsKt87iDN-FNw,2,0,0,0,One of the few places in town you can view wor...,2015-11-18 22:20:55,...,NV,89109,36.112896,-115.177637,3.5,180,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Shopping, Arts & Entertainment, Art Galleries,...","{'Monday': '10:0-20:0', 'Tuesday': '10:0-20:0'..."
4,34353,cnV5xtm6WuyaLfot9uWbDg,LkWNo83Lg92C5V4JEyxOZA,-MhfebM0QIsKt87iDN-FNw,3,3,1,2,This is a hard one to review. I was excited to...,2010-10-10 01:27:31,...,NV,89109,36.112896,-115.177637,3.5,180,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Shopping, Arts & Entertainment, Art Galleries,...","{'Monday': '10:0-20:0', 'Tuesday': '10:0-20:0'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8021117,8016096,yJJtiOJ-p1nUkwtFEd8PWg,Mkb6AzO-2X2S5fdt6OrInQ,66uR6KGQpVNYzYXcLwvLmg,1,2,1,0,A very bad job had to do it over n still not r...,2018-08-13 20:21:19,...,OH,44109,41.418991,-81.690923,3.5,3,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Auto Repair, Automotive, Auto Detailing, Body ...","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ..."
8021118,8017300,UkhGGypImTcMYsqeNmO-kA,Lzqisc3p6b9s4CxOQPEPXw,66uR6KGQpVNYzYXcLwvLmg,5,5,1,1,I've dealt with A Touch of Class several times...,2017-04-08 20:31:17,...,OH,44109,41.418991,-81.690923,3.5,3,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Auto Repair, Automotive, Auto Detailing, Body ...","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ..."
8021119,8014945,Dh8X9r_uxhhtRU-0z-AroA,q5GPWlNDO_8xEyn0SoqYiA,gupf_nysqVXsCkmJJjIgEw,1,0,0,0,Very prompt email response.\nHe has good revie...,2019-11-12 19:25:58,...,ON,M1N 1N1,43.706165,-79.249938,3.5,3,1,{'ByAppointmentOnly': 'False'},"Professional Services, Office Cleaning, Home C...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
8021120,8017647,Y2q7-ExUvXr32_PYxad28Q,wCsohq112DNRAYWXXNnemw,gupf_nysqVXsCkmJJjIgEw,5,0,0,0,We have used TorontoCleaningSolutions & office...,2019-11-29 23:01:03,...,ON,M1N 1N1,43.706165,-79.249938,3.5,3,1,{'ByAppointmentOnly': 'False'},"Professional Services, Office Cleaning, Home C...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
8021121,8019597,No5DaA47bGRRqMnrEPQ2XQ,lEbDfbJsC70xltar8OxbHg,gupf_nysqVXsCkmJJjIgEw,5,0,0,0,I had the pleasure of hiring Toronto Cleaning ...,2019-10-15 03:51:05,...,ON,M1N 1N1,43.706165,-79.249938,3.5,3,1,{'ByAppointmentOnly': 'False'},"Professional Services, Office Cleaning, Home C...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."

In [6]:
all_data_open_res = all_data_open[all_data_open['categories'].str.contains('Restaurant', na=False)]
all_data_open_res

,Unnamed: 0_x,review_id,user_id,business_id,stars_x,useful,funny,cool,text,date,...,state,postal_code,latitude,longitude,stars_y,review_count,is_open,attributes,categories,hours
189,2,LG2ZaYiOgpr2DK_90pYjNw,V34qejxNsCbcgD8C0HVk-Q,HQl28KMwrEKHqhFrrDqVNQ,5,1,0,0,I love Deagan's. I do. I really do. The atmosp...,2015-12-05 03:18:11,...,OH,44107,41.485192,-81.800145,4.0,417,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Restaurants, Gastropubs, Nightlife, American (...","{'Tuesday': '11:0-22:0', 'Wednesday': '11:0-22..."
190,2870,4jMOeTiqNXQ8bpmFdWoFUQ,zFCuveEe6M-ijY1iy23IJg,HQl28KMwrEKHqhFrrDqVNQ,5,6,2,5,"We walked into Melt. ""Did you want to put your...",2011-08-25 04:24:23,...,OH,44107,41.485192,-81.800145,4.0,417,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Restaurants, Gastropubs, Nightlife, American (...","{'Tuesday': '11:0-22:0', 'Wednesday': '11:0-22..."
191,6586,wHrtQRyk0ypungXd6hT8nQ,4V985R3RG-rv0B7WCPQzeQ,HQl28KMwrEKHqhFrrDqVNQ,1,1,0,0,I commented on how slow the service was last A...,2015-03-04 20:37:43,...,OH,44107,41.485192,-81.800145,4.0,417,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Restaurants, Gastropubs, Nightlife, American (...","{'Tuesday': '11:0-22:0', 'Wednesday': '11:0-22..."
192,7891,DTb3X5aVOGQ8HHCSAr87wA,nFGcoL6wuPQzxsNJVSfGrA,HQl28KMwrEKHqhFrrDqVNQ,4,2,0,0,We walked in off the streets on a September ni...,2014-09-10 01:38:55,...,OH,44107,41.485192,-81.800145,4.0,417,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Restaurants, Gastropubs, Nightlife, American (...","{'Tuesday': '11:0-22:0', 'Wednesday': '11:0-22..."
193,8274,NPyAutqgU_zIZBSnycJd6w,CJqgUQeWhdgbDyLAFy7xvQ,HQl28KMwrEKHqhFrrDqVNQ,4,0,0,0,Brunch on Saturday was excellent. The Bloody M...,2018-01-21 18:50:29,...,OH,44107,41.485192,-81.800145,4.0,417,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Restaurants, Gastropubs, Nightlife, American (...","{'Tuesday': '11:0-22:0', 'Wednesday': '11:0-22..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8021088,8015990,7chRxkhJRh9jF9FHYPINBA,UIuD_Nz1sEPoL0enb8SWGw,ObHV12Mb9IaGQQ01-7x-PQ,1,0,0,0,Had lunch with my wife here today. Never been ...,2019-12-01 22:03:29,...,NC,28037,35.447423,-81.002387,2.5,3,1,NaN,"Salad, Restaurants, Chicken Wings, Pizza, Sand...","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
8021089,8020406,ygYn6vqKuWy_YbrTxGe-QA,2el5y-jw8bgWkvzJ0cmDkw,ObHV12Mb9IaGQQ01-7x-PQ,5,0,0,0,"Great atmosphere, dine in, kid friendly! Top q...",2019-11-30 06:14:24,...,NC,28037,35.447423,-81.002387,2.5,3,1,NaN,"Salad, Restaurants, Chicken Wings, Pizza, Sand...","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
8021090,8002522,9ESd29mlsMoZaHZ3lZLd0A,bAeolHM20hU68z58zmm5gw,FAKL5o4QWW_DrLxG20GwzQ,1,1,1,1,Small selection of drinks. Coffee wasn't great...,2019-10-07 00:43:58,...,WI,53716,43.047740,-89.337122,3.5,3,1,"{'BusinessParking': ""{'garage': False, 'street...","Restaurants, Coffee Roasteries, Sandwiches, Co...","{'Monday': '6:0-19:0', 'Tuesday': '6:0-19:0', ..."
8021091,8010854,5aUMu34pwsmTQ-Hl-VUZfw,SOegnrCTG9gPmrQMU6x82A,FAKL5o4QWW_DrLxG20GwzQ,4,0,0,0,Nice atmosphere and good background music. Gre...,2019-11-09 15:15:53,...,WI,53716,43.047740,-89.337122,3.5,3,1,"{'BusinessParking': ""{'garage': False, 'street...","Restaurants, Coffee Roasteries, Sandwiches, Co...","{'Monday': '6:0-19:0', 'Tuesday': '6:0-19:0', ..."
8021092,8016413,yq0c4VCzIvMBdCKFln84ew,UYtkKjVMkPY2Dbzq8ESYCQ,FAKL5o4QWW_DrLxG20GwzQ,5,1,0,0,So excited that the new cafe is on my daily co...,2019-09-17 16:56:49,...,WI,53716,43.047740,-89.337122,3.5,3,1,"{'BusinessParking': ""{'garage': False, 'street...","Restaurants, Coffee Roasteries, Sandwiches, Co...","{'Monday': '6:0-19:0', 'Tuesday': '6:0-19:0', ..."

In [10]:
user = pd.read_csv('yelp_user.csv')

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (14) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [11]:
all_data_open_res = pd.merge(all_data_open_res, user, on='user_id')
all_data_open_res

,Unnamed: 0,Unnamed: 0_x,review_id,user_id,business_id,stars_x,useful_x,funny_x,cool_x,text,...,average_stars,cool_y,elite,compliment_cute,friends,compliment_cool,compliment_list,compliment_writer,compliment_more,compliment_note
0,189,2,LG2ZaYiOgpr2DK_90pYjNw,V34qejxNsCbcgD8C0HVk-Q,HQl28KMwrEKHqhFrrDqVNQ,5,1,0,0.0,I love Deagan's. I do. I really do. The atmosp...,...,4.02,126,"2015,2016,2017,2018",2,"ZlOgxIThXJYkHPLj2fiYAw, XZg_60BabYR1t2aGqN10PQ...",13,0,7,1,3
1,198947,651056,jCza0LPv1vNU0FF-NFMWQA,V34qejxNsCbcgD8C0HVk-Q,ErxACeMyF4hSQyGhpEt4Tw,5,1,1,1.0,This is definitely one of my favorite Thai res...,...,4.02,126,"2015,2016,2017,2018",2,"ZlOgxIThXJYkHPLj2fiYAw, XZg_60BabYR1t2aGqN10PQ...",13,0,7,1,3
2,210539,528744,14_N-s_7TsEpzgjnXJMu9Q,V34qejxNsCbcgD8C0HVk-Q,eoJfl5vG7X87QhcKb0nt5Q,4,4,1,3.0,This is exactly what you think it will be. A h...,...,4.02,126,"2015,2016,2017,2018",2,"ZlOgxIThXJYkHPLj2fiYAw, XZg_60BabYR1t2aGqN10PQ...",13,0,7,1,3
3,309591,209502,eE3ekstCj5dNcBJVsbOJBw,V34qejxNsCbcgD8C0HVk-Q,VH2BjFjc9usDquDgoHhptA,4,2,0,2.0,How exciting to have another great Barrio loca...,...,4.02,126,"2015,2016,2017,2018",2,"ZlOgxIThXJYkHPLj2fiYAw, XZg_60BabYR1t2aGqN10PQ...",13,0,7,1,3
4,322590,585352,B6-F7JQzRIiMQpphyPR3VA,V34qejxNsCbcgD8C0HVk-Q,0youcKV6-eE3F2MQj1l6Fw,4,1,0,1.0,I attended a group event here with about 80 pe...,...,4.02,126,"2015,2016,2017,2018",2,"ZlOgxIThXJYkHPLj2fiYAw, XZg_60BabYR1t2aGqN10PQ...",13,0,7,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4223196,8021070,8018377,GI6YNX2dsf2zsEAjZo2piQ,JLlI9YRhlE3l098RASlxJg,ypPX33g0adYkh2KpYnj0eQ,5,0,0,0.0,I go to this location every weekend to get my ...,...,5.00,0,NaN,0,DLE8tNZMah8jwi0gEs2bFA,0,0,0,0,0
4223197,8021087,7998432,RokMKfYCWBD9lAtEwpCiCw,Iq5eulb9D392-2wxYq33LA,ObHV12Mb9IaGQQ01-7x-PQ,1,1,0,0.0,Ordered pizza for delivery and still has not b...,...,3.00,0,NaN,0,"UeVfOeO-c00U6IfefbNW1Q, -RHwP3iZqpMsrhWydC4z4Q...",0,0,0,0,0
4223198,8021088,8015990,7chRxkhJRh9jF9FHYPINBA,UIuD_Nz1sEPoL0enb8SWGw,ObHV12Mb9IaGQQ01-7x-PQ,1,0,0,0.0,Had lunch with my wife here today. Never been ...,...,3.78,0,NaN,0,None,0,0,0,0,0
4223199,8021089,8020406,ygYn6vqKuWy_YbrTxGe-QA,2el5y-jw8bgWkvzJ0cmDkw,ObHV12Mb9IaGQQ01-7x-PQ,5,0,0,0.0,"Great atmosphere, dine in, kid friendly! Top q...",...,5.00,0,NaN,0,None,0,0,0,0,0
4223200,8021090,8002522,9ESd29mlsMoZaHZ3lZLd0A,bAeolHM20hU68z58zmm5gw,FAKL5o4QWW_DrLxG20GwzQ,1,1,1,1.0,Small selection of drinks. Coffee wasn't great...,...,1.00,1,NaN,0,"XAQh8bUBhbMtD3-9vrZiIQ, DxuCWFl9r0_c4uxDmLDw7Q...",0,0,0,0,0

In [12]:
all_data_open_res.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4223201 entries, 0 to 4223200
Data columns (total 46 columns):
 #   Column              Dtype
---  ------              -----
 0   Unnamed: 0          object
 1   Unnamed: 0_x        object
 2   review_id           object
 3   user_id             object
 4   business_id         object
 5   stars_x             object
 6   useful_x            object
 7   funny_x             int64
 8   cool_x              float64
 9   text                object
 10  date                object
 11  Unnamed: 0_y        float64
 12  name_x              object
 13  address             object
 14  city                object
 15  state               object
 16  postal_code         object
 17  latitude            float64
 18  longitude           float64
 19  stars_y             float64
 20  review_count_x      float64
 21  is_open             float64
 22  attributes          object
 23  categories          object
 24  hours               object
 25  funny_y             int64
 26  review_count_y      int64
 27  compliment_hot      int64
 28  compliment_funny    int64
 29  compliment_plain    int64
 30  fans                int64
 31  compliment_photos   int64
 32  compliment_profile  int64
 33  useful_y            int64
 34  yelping_since       object
 35  name_y              object
 36  average_stars       float64
 37  cool_y              int64
 38  elite               object
 39  compliment_cute     int64
 40  friends             object
 41  compliment_cool     int64
 42  compliment_list     int64
 43  compliment_writer   int64
 44  compliment_more     int64
 45  compliment_note     int64
dtypes: float64(8), int64(17), object(21)
memory usage: 1.5+ GB

In [13]:
all_data_open_res = all_data_open_res.rename({'stars_x':'stars_r', 'useful_x':'useful_r', 'funny_x':'funny_r', 'cool_x':'cool_r',
                  'name_x': 'name_b', 'stars_y':'stars_b', 'review_count_x':'review_count_b',
                  'funny_y':'funny_u', 'review_count_y':'review_count_u', 'useful_y':'useful_u', 'name_y':'name_u', 'cool_y':'cool_u'}, axis=1)

In [14]:
all_data_open_res

,Unnamed: 0,Unnamed: 0_x,review_id,user_id,business_id,stars_r,useful_r,funny_r,cool_r,text,...,average_stars,cool_u,elite,compliment_cute,friends,compliment_cool,compliment_list,compliment_writer,compliment_more,compliment_note
0,189,2,LG2ZaYiOgpr2DK_90pYjNw,V34qejxNsCbcgD8C0HVk-Q,HQl28KMwrEKHqhFrrDqVNQ,5,1,0,0.0,I love Deagan's. I do. I really do. The atmosp...,...,4.02,126,"2015,2016,2017,2018",2,"ZlOgxIThXJYkHPLj2fiYAw, XZg_60BabYR1t2aGqN10PQ...",13,0,7,1,3
1,198947,651056,jCza0LPv1vNU0FF-NFMWQA,V34qejxNsCbcgD8C0HVk-Q,ErxACeMyF4hSQyGhpEt4Tw,5,1,1,1.0,This is definitely one of my favorite Thai res...,...,4.02,126,"2015,2016,2017,2018",2,"ZlOgxIThXJYkHPLj2fiYAw, XZg_60BabYR1t2aGqN10PQ...",13,0,7,1,3
2,210539,528744,14_N-s_7TsEpzgjnXJMu9Q,V34qejxNsCbcgD8C0HVk-Q,eoJfl5vG7X87QhcKb0nt5Q,4,4,1,3.0,This is exactly what you think it will be. A h...,...,4.02,126,"2015,2016,2017,2018",2,"ZlOgxIThXJYkHPLj2fiYAw, XZg_60BabYR1t2aGqN10PQ...",13,0,7,1,3
3,309591,209502,eE3ekstCj5dNcBJVsbOJBw,V34qejxNsCbcgD8C0HVk-Q,VH2BjFjc9usDquDgoHhptA,4,2,0,2.0,How exciting to have another great Barrio loca...,...,4.02,126,"2015,2016,2017,2018",2,"ZlOgxIThXJYkHPLj2fiYAw, XZg_60BabYR1t2aGqN10PQ...",13,0,7,1,3
4,322590,585352,B6-F7JQzRIiMQpphyPR3VA,V34qejxNsCbcgD8C0HVk-Q,0youcKV6-eE3F2MQj1l6Fw,4,1,0,1.0,I attended a group event here with about 80 pe...,...,4.02,126,"2015,2016,2017,2018",2,"ZlOgxIThXJYkHPLj2fiYAw, XZg_60BabYR1t2aGqN10PQ...",13,0,7,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4223196,8021070,8018377,GI6YNX2dsf2zsEAjZo2piQ,JLlI9YRhlE3l098RASlxJg,ypPX33g0adYkh2KpYnj0eQ,5,0,0,0.0,I go to this location every weekend to get my ...,...,5.00,0,NaN,0,DLE8tNZMah8jwi0gEs2bFA,0,0,0,0,0
4223197,8021087,7998432,RokMKfYCWBD9lAtEwpCiCw,Iq5eulb9D392-2wxYq33LA,ObHV12Mb9IaGQQ01-7x-PQ,1,1,0,0.0,Ordered pizza for delivery and still has not b...,...,3.00,0,NaN,0,"UeVfOeO-c00U6IfefbNW1Q, -RHwP3iZqpMsrhWydC4z4Q...",0,0,0,0,0
4223198,8021088,8015990,7chRxkhJRh9jF9FHYPINBA,UIuD_Nz1sEPoL0enb8SWGw,ObHV12Mb9IaGQQ01-7x-PQ,1,0,0,0.0,Had lunch with my wife here today. Never been ...,...,3.78,0,NaN,0,None,0,0,0,0,0
4223199,8021089,8020406,ygYn6vqKuWy_YbrTxGe-QA,2el5y-jw8bgWkvzJ0cmDkw,ObHV12Mb9IaGQQ01-7x-PQ,5,0,0,0.0,"Great atmosphere, dine in, kid friendly! Top q...",...,5.00,0,NaN,0,None,0,0,0,0,0
4223200,8021090,8002522,9ESd29mlsMoZaHZ3lZLd0A,bAeolHM20hU68z58zmm5gw,FAKL5o4QWW_DrLxG20GwzQ,1,1,1,1.0,Small selection of drinks. Coffee wasn't great...,...,1.00,1,NaN,0,"XAQh8bUBhbMtD3-9vrZiIQ, DxuCWFl9r0_c4uxDmLDw7Q...",0,0,0,0,0

In [15]:
all_data_open_res['state'].value_counts()

NV     1410254
AZ     1214917
ON      537465
NC      289133
OH      233714
PA      209723
QC      138625
WI       87719
AB       58917
IL       25883
SC       16318
NY         128
CA          95
TX          92
HI          51
CO          45
MB          36
VA          27
NE          18
FL          10
OR           9
BC           6
VT           5
AL           4
WA           3
HPL          3
Name: state, dtype: int64

In [18]:
all_filter_nv = all_data_open_res[all_data_open_res['state']=='NV']

In [19]:
all_filter_nv

,Unnamed: 0,Unnamed: 0_x,review_id,user_id,business_id,stars_r,useful_r,funny_r,cool_r,text,...,average_stars,cool_u,elite,compliment_cute,friends,compliment_cool,compliment_list,compliment_writer,compliment_more,compliment_note
38,852432,1428821,dokQIMcveyRcoqaTghiUMA,zFCuveEe6M-ijY1iy23IJg,P7pxQFqr7yBKMMI2J51udw,4,1,1,1.0,My first trip to Vegas was a total culinary di...,...,3.52,312,"2011,2012,2013,2014",0,"WxhyL947DCT78nDnPOJ2Iw, Zd4dJE4ZbEyq8Q3soq_YRg...",69,2,29,5,30
72,5005872,5165282,pN4hqX_6Bb8nxu_9U720cw,zFCuveEe6M-ijY1iy23IJg,N7yuiiu8jhQ-Fl9Npflreg,2,2,2,0.0,Are you people on crack? This food was downrig...,...,3.52,312,"2011,2012,2013,2014",0,"WxhyL947DCT78nDnPOJ2Iw, Zd4dJE4ZbEyq8Q3soq_YRg...",69,2,29,5,30
78,5750928,5862280,uyrnduQmgFHRMt_8lOIMCQ,zFCuveEe6M-ijY1iy23IJg,TVbVii4EUQt9DG7y698zIw,1,2,1,1.0,"Meh, not much to say here.\n\nI ordered the ma...",...,3.52,312,"2011,2012,2013,2014",0,"WxhyL947DCT78nDnPOJ2Iw, Zd4dJE4ZbEyq8Q3soq_YRg...",69,2,29,5,30
121,3692900,3977478,5-qw7FK5y4qB6fRZbRodHw,nFGcoL6wuPQzxsNJVSfGrA,RVNxhRf8ERTAb38vBWvCig,1,1,2,0.0,"The lettuce was brown, the burger was disgusti...",...,3.20,20,NaN,0,"kzFo3oanpMaJuSUrGIcrFA, BHmLSf47AKTmlEw3uCXY9Q...",1,0,0,0,3
482,1075682,1334815,EEzO2FQAl6V15j6ITXWilA,alxetHC3mXR2PtG8CeCN6Q,znWHLW1pt19HzW1VY6KfCA,5,0,0,0.0,This place is delicious but you better come hu...,...,4.12,85,NaN,0,"piNLBRhgGoQ7lh9vlVbPFQ, Jy2M47ciQztl7w_HcrN3sg...",2,0,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4223170,8020159,7886379,tEXwLl3dlIsMbo9YcbyAdQ,HZMy4mEF_tKhVaIrBHPU9w,cZrtB-AWUd1BQSGchnTbIw,5,1,0,0.0,"Keep it simple BETTER THEN SUBWAY, and jimmy j...",...,4.80,0,NaN,0,"XDyAxxv9YrSUK5qPdaamMw, 4xpOaWKjM9c_MZIUFW3ygw...",0,0,0,0,0
4223171,8020180,7918513,LKh2HsjBkZG_q3zDHvxE4A,UzzgtBc38t-MaMg3dYtzmA,2FH_za_zymEcQSpO_y5P1g,5,0,1,0.0,I have used Rigo on many occasions from regula...,...,5.00,1,NaN,0,"A3oPeCMjfgO8VDhj55EqXw, Zv2n4yy_4UFHMFwaifdfoA...",0,0,0,0,0
4223172,8020182,7975721,eqkqSkKCKtcgfDOP_M8OVg,RSuSgmaX0fW4l0xrQiivrw,2FH_za_zymEcQSpO_y5P1g,5,0,1,0.0,"Excellent job, he did the impossible. He conve...",...,4.50,0,NaN,0,None,0,0,0,0,0
4223173,8020183,8001469,38NzCbjBvhdV4QxrpA-gwg,kUWiHl3EoKLudcCKc3F66A,2FH_za_zymEcQSpO_y5P1g,5,0,1,0.0,I would recommend Rico stone floor restoration...,...,3.56,9,NaN,0,"z6OUh5BuqZCM55XI3aK6JQ, sbzVHatqEloTQ0WPs32XCA...",0,0,0,0,0
4223179,8020405,7980235,ePXwx5sSke62nAYNRAuzcw,AC-JrmOJ_mUKCEVl7xyXNQ,g124aGBLCH0YyeTaWnjgrQ,5,0,0,0.0,"I am an east coaster, now living in las vegas ...",...,3.17,0,NaN,0,"MfMGga45WZvb0vljgJSxjQ, sVSr9-Kt1OTjVRiTQ-29Jg...",0,0,0,0,0

In [24]:
all_filter_nv.to_csv('filted_nv.csv')

In [26]:
all_filter_on = all_data_open_res[all_data_open_res['state']=='ON']
all_filter_on

,Unnamed: 0,Unnamed: 0_x,review_id,user_id,business_id,stars_r,useful_r,funny_r,cool_r,text,...,average_stars,cool_u,elite,compliment_cute,friends,compliment_cool,compliment_list,compliment_writer,compliment_more,compliment_note
1113,1109723,1248251,DqNeDzg6DR0AJ9XgVLWdog,sxEzazybwfF86Mv8Dm3tgw,ejKXczjEkm1gzyRdblQm8w,5,2,0,0.0,Fresh is a really great name for this place! ...,...,4.43,406,"2015,2016,2017,2018",0,"bN9UQdyftA92BZAy_r3yAw, uYIqEXZmQQkXzBRUDMtz6A...",16,0,10,2,11
1115,1312051,1247091,6ugTMgiAj6Fh4-GTS6VuWQ,sxEzazybwfF86Mv8Dm3tgw,fQwB9Z98YEhkJit7c3z51A,4,0,0,0.0,Great selection of bar snacks. We loved the K...,...,4.43,406,"2015,2016,2017,2018",0,"bN9UQdyftA92BZAy_r3yAw, uYIqEXZmQQkXzBRUDMtz6A...",16,0,10,2,11
1117,2476008,2441043,zn12kMDI624hVCDeBJX35A,sxEzazybwfF86Mv8Dm3tgw,r_BrIgzYcwo1NAuG9dLbpg,4,0,0,0.0,We stopped here for drinks before dinner reser...,...,4.43,406,"2015,2016,2017,2018",0,"bN9UQdyftA92BZAy_r3yAw, uYIqEXZmQQkXzBRUDMtz6A...",16,0,10,2,11
1119,2855876,2978774,ScStrfHpPbfQNCCCXleQzA,sxEzazybwfF86Mv8Dm3tgw,XdY36-Qh_DxnCaFpTPfYMg,5,0,0,0.0,Oh my my.... This place was on my list of dest...,...,4.43,406,"2015,2016,2017,2018",0,"bN9UQdyftA92BZAy_r3yAw, uYIqEXZmQQkXzBRUDMtz6A...",16,0,10,2,11
1124,5194241,5344071,iP-4hTON1YYrTSANzGuzCg,sxEzazybwfF86Mv8Dm3tgw,nOmR49imE4GtmwWVLkHS9A,5,0,0,0.0,I'm surprised at the negative reviews. We fou...,...,4.43,406,"2015,2016,2017,2018",0,"bN9UQdyftA92BZAy_r3yAw, uYIqEXZmQQkXzBRUDMtz6A...",16,0,10,2,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4223186,8020789,7926855,Q9BJQbua2vq69OLOKjJuzQ,R1Qolz0gwdLW82dLweV53w,8GBmys1QbunrRRnXOhlLeg,5,0,0,0.0,I was really excited to try this place after I...,...,5.00,0,NaN,0,None,0,0,0,0,0
4223193,8021049,7975564,xHtfpbO_QxEvg0syQ2dKTQ,YYuStuzyYtZZA2EWpxq6eA,fHtlB9RhRxgxCQjBXdIt1Q,4,0,0,0.0,"I found Patricia's ad via kijiji, and saw that...",...,4.00,0,NaN,0,None,0,0,0,0,0
4223194,8021051,8007384,ZbB1PCvg20OMo-ENls6fsg,unraC85fHLQR_uxqPLOwbA,fHtlB9RhRxgxCQjBXdIt1Q,1,0,0,0.0,Wish there is a 0 star for her. This is the mo...,...,1.00,0,NaN,0,None,0,0,0,0,0
4223195,8021068,7987230,SVWdmOsz_M_aQCEqzm9Riw,U6NGzchRVOX1Ino_IyGk0g,ypPX33g0adYkh2KpYnj0eQ,1,1,0,0.0,A joke of a place that is giving a very bad na...,...,2.60,3,NaN,0,"LR7r5Ug1ZnPzeSykBJsvbQ, 4kp_PxKDLzVW8wpQOQmH2g...",0,0,0,0,0
4223196,8021070,8018377,GI6YNX2dsf2zsEAjZo2piQ,JLlI9YRhlE3l098RASlxJg,ypPX33g0adYkh2KpYnj0eQ,5,0,0,0.0,I go to this location every weekend to get my ...,...,5.00,0,NaN,0,DLE8tNZMah8jwi0gEs2bFA,0,0,0,0,0

In [27]:
all_filter_on.to_csv('filted_on.csv')